version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh /app/entrypoint.sh python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - /app/venv
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend

  mobile:
    build:
      context: ./mobile
      dockerfile: Dockerfile
    tty: true            # <--- KLUCZOWE: Włącza emulację terminala (pozwala rysować kod QR)
    stdin_open: true      # <--- Pozwala na interakcję (np. naciskanie klawiszy w logach)
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
    volumes:
      - ./mobile:/app
      - /app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.100.155 # Upewnij się, że to Twoje IP lokalne!
    command: npx expo start --tunnel

volumes:
  db_data: