# Generated by Django 5.1 on 2025-08-09 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("portfolios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                (
                    "side",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")],
                        default="BUY",
                        max_length=4,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=20)),
                ("price", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "fee",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                ("executed_at", models.DateTimeField()),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-executed_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TransactionPortfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolios.portfolio",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transactions.transaction",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="transaction",
            name="portfolios",
            field=models.ManyToManyField(
                blank=True,
                related_name="transactions",
                through="transactions.TransactionPortfolio",
                to="portfolios.portfolio",
            ),
        ),
        migrations.AddIndex(
            model_name="transactionportfolio",
            index=models.Index(
                fields=["portfolio"], name="transaction_portfol_4c0c01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transactionportfolio",
            index=models.Index(
                fields=["transaction"], name="transaction_transac_8d2db9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="transactionportfolio",
            unique_together={("transaction", "portfolio")},
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["owner", "symbol"], name="transaction_owner_i_e308f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["owner", "executed_at"], name="transaction_owner_i_766807_idx"
            ),
        ),
    ]
