# Generated by Django 5.1 on 2026-02-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='asset_type',
            field=models.CharField(choices=[('stock', 'Stock'), ('crypto', 'Crypto')], default='stock', max_length=10),
        ),
    ]
