# Generated by Django 5.1 on 2025-08-10 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_google_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_google_account',
        ),
    ]
