# Generated by Django 5.1 on 2025-08-09 09:49

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["owner_id", "name"],
                "indexes": [
                    models.Index(
                        fields=["owner", "name"], name="portfolios__owner_i_c9308c_idx"
                    ),
                    models.Index(
                        django.db.models.functions.text.Lower("name"),
                        name="idx_portfolio_lower_name",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        models.F("owner"),
                        name="uq_portfolio_owner_lower_name",
                    )
                ],
            },
        ),
    ]
